### ISSUE TITLE
Tmall genie and Kingsmith Treadmill

### ISSUE THREAD

**Issue by maxdd** [sepnic/tmallgenie_open#2]
Hello,
a long time ago i bought a really nice treadmill from aliexpress. The model is a kingsmith trf12 but only later i've discovered that the blue version i have can only be used via WiFi and tmall genie app.
Unfortunately i have no knowloedge of chinese language :/ and apparently i would also need a chinese phone number (+89) to even have an account (i didnt really try hard though).
I'm wondering whether this project can help me somehow to figure out how to extract from the cloud or from the device itself (treadmill + remote (wifi?) ) the data of my jogging sessions

btw it seems the treadmill is expected to be paired with 天猫精灵 which if im not wrong are the smart speaker (which i don't have)

**Comment by sepnic** [comment]
Unfortunately, this project won't help with your problem.
Actually you need pair the treadmill with  "Tmall Genie" (天猫精灵 in Chinese) app, not smart speaker. And to login "Tmall Genie" app, you have to own a Chinese phone number...AFAIK, Tmall Genie doesn't work outside China mainland.

**Comment by maxdd** [comment]
i see. thank you!
